AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an Amazon ECR repository with a lifecycle policy.'

Parameters:
  RepositoryName:
    Type: String
    Default: my-ecr-repo
    Description: Name of the ECR repository

Resources:
  ECRRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageTagMutability: IMMUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire images older than latest 7",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 7
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryUri:
    Description: 'URI of the created ECR repository'
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub "${AWS::StackName}-RepositoryUri"

