apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  DB_HOST: 'REPLACE_DB_HOST'
  DB_PORT: 'REPLACE_DB_PORT'
  DB_USERNAME: 'REPLACE_DB_USERNAME'
  DB_NAME: 'REPLACE_DB_NAME'
  LOCAL_API_SECRET: 'REPLACE_LOCAL_API_SECRET'